# Generated by Django 3.0.5 on 2021-05-09 06:14

import API.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('time', models.CharField(max_length=30)),
                ('value', models.CharField(max_length=30)),
                ('mode', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('houseID', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('house_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('devices', djongo.models.fields.EmbeddedField(model_container=API.models.Device)),
            ],
        ),
    ]
