# Generated by Django 3.0.5 on 2021-05-12 12:20

import API.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DevicesAdmin',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', primary_key=True, serialize=False)),
                ('home_id', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(default='Need a string there', max_length=30)),
                ('time', models.CharField(max_length=30)),
                ('value', models.CharField(max_length=30)),
                ('mode', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', primary_key=True, serialize=False)),
                ('home_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('devices', djongo.models.fields.ArrayField(blank=True, model_container=API.models.Device, null=True)),
            ],
        ),
    ]
