# Generated by Django 3.0.5 on 2021-05-23 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='value',
            field=models.CharField(max_length=100),
        ),
    ]
