# Generated by Django 3.0.5 on 2021-05-13 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='phone_number',
            field=models.CharField(default='required phone number', max_length=30, unique=True),
        ),
    ]
