# Generated by Django 3.0.5 on 2021-05-09 06:34

import API.models
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='devices',
            field=djongo.models.fields.EmbeddedField(blank=True, model_container=API.models.Device, null=True),
        ),
    ]
