# Generated by Django 3.0.5 on 2021-05-21 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DevicesAdmin',
        ),
    ]
