# Generated by Django 3.0.5 on 2021-05-23 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20210523_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='history',
            name='unit',
        ),
    ]
